package com.example.mykeyboard.model

import android.graphics.Color

enum class KeyboardTheme(
    val id: String,
    val displayName: String,
    val backgroundColor: Int,
    val keyNormalColor: Int,
    val keySpecialColor: Int,
    val keyActionColor: Int,
    val keySpaceColor: Int,
    val textColorPrimary: Int,
    val textColorSecondary: Int,
    val actionTextColor: Int,
    val suggestionBgColor: Int,
    val suggestionTextColor: Int,
    val popupBgColor: Int,
    val popupTextColor: Int,
    val rippleColor: Int,
    val isDark: Boolean
) {
    AMOLED_MIDNIGHT(
        id = "amoled_midnight",
        displayName = "AMOLED Pitch Black (OLED)",
        backgroundColor = Color.parseColor("#000000"),
        keyNormalColor = Color.parseColor("#141414"),
        keySpecialColor = Color.parseColor("#222222"),
        keyActionColor = Color.parseColor("#007AFF"),
        keySpaceColor = Color.parseColor("#141414"),
        textColorPrimary = Color.parseColor("#FFFFFF"),
        textColorSecondary = Color.parseColor("#8E8E93"),
        actionTextColor = Color.parseColor("#FFFFFF"),
        suggestionBgColor = Color.parseColor("#000000"),
        suggestionTextColor = Color.parseColor("#FFFFFF"),
        popupBgColor = Color.parseColor("#2C2C2E"),
        popupTextColor = Color.parseColor("#FFFFFF"),
        rippleColor = Color.parseColor("#3A3A3C"),
        isDark = true
    ),
    MATTE_DARK(
        id = "material_dark",
        displayName = "Gboard Dark Slate",
        backgroundColor = Color.parseColor("#18181B"),
        keyNormalColor = Color.parseColor("#27272A"),
        keySpecialColor = Color.parseColor("#3F3F46"),
        keyActionColor = Color.parseColor("#3B82F6"),
        keySpaceColor = Color.parseColor("#27272A"),
        textColorPrimary = Color.parseColor("#F4F4F5"),
        textColorSecondary = Color.parseColor("#A1A1AA"),
        actionTextColor = Color.parseColor("#FFFFFF"),
        suggestionBgColor = Color.parseColor("#18181B"),
        suggestionTextColor = Color.parseColor("#F4F4F5"),
        popupBgColor = Color.parseColor("#27272A"),
        popupTextColor = Color.parseColor("#F4F4F5"),
        rippleColor = Color.parseColor("#52525B"),
        isDark = true
    ),
    PASTEL_PINK_BLUSH(
        id = "gboard_peach",
        displayName = "Pastel Pink Blush",
        backgroundColor = Color.parseColor("#FDF2F4"),
        keyNormalColor = Color.parseColor("#FFFFFF"),
        keySpecialColor = Color.parseColor("#FCE7F3"),
        keyActionColor = Color.parseColor("#F43F5E"),
        keySpaceColor = Color.parseColor("#FFFFFF"),
        textColorPrimary = Color.parseColor("#1E293B"),
        textColorSecondary = Color.parseColor("#94A3B8"),
        actionTextColor = Color.parseColor("#FFFFFF"),
        suggestionBgColor = Color.parseColor("#FDF2F4"),
        suggestionTextColor = Color.parseColor("#1E293B"),
        popupBgColor = Color.parseColor("#FFFFFF"),
        popupTextColor = Color.parseColor("#1E293B"),
        rippleColor = Color.parseColor("#FBCFE8"),
        isDark = false
    ),
    CYBER_NEON_NIGHT(
        id = "cyber_neon",
        displayName = "Cyber Neon Cyan",
        backgroundColor = Color.parseColor("#0F172A"),
        keyNormalColor = Color.parseColor("#1E293B"),
        keySpecialColor = Color.parseColor("#334155"),
        keyActionColor = Color.parseColor("#06B6D4"),
        keySpaceColor = Color.parseColor("#1E293B"),
        textColorPrimary = Color.parseColor("#F8FAFC"),
        textColorSecondary = Color.parseColor("#38BDF8"),
        actionTextColor = Color.parseColor("#0F172A"),
        suggestionBgColor = Color.parseColor("#0F172A"),
        suggestionTextColor = Color.parseColor("#F8FAFC"),
        popupBgColor = Color.parseColor("#1E293B"),
        popupTextColor = Color.parseColor("#F8FAFC"),
        rippleColor = Color.parseColor("#475569"),
        isDark = true
    ),
    FOREST_EMERALD(
        id = "emerald_green",
        displayName = "Forest Emerald",
        backgroundColor = Color.parseColor("#064E3B"),
        keyNormalColor = Color.parseColor("#047857"),
        keySpecialColor = Color.parseColor("#065F46"),
        keyActionColor = Color.parseColor("#10B981"),
        keySpaceColor = Color.parseColor("#047857"),
        textColorPrimary = Color.parseColor("#ECFDF5"),
        textColorSecondary = Color.parseColor("#A7F3D0"),
        actionTextColor = Color.parseColor("#064E3B"),
        suggestionBgColor = Color.parseColor("#064E3B"),
        suggestionTextColor = Color.parseColor("#ECFDF5"),
        popupBgColor = Color.parseColor("#047857"),
        popupTextColor = Color.parseColor("#ECFDF5"),
        rippleColor = Color.parseColor("#059669"),
        isDark = true
    ),
    ROYAL_PURPLE(
        id = "royal_purple",
        displayName = "Royal Purple Midnight",
        backgroundColor = Color.parseColor("#2E1065"),
        keyNormalColor = Color.parseColor("#3B0764"),
        keySpecialColor = Color.parseColor("#581C87"),
        keyActionColor = Color.parseColor("#A855F7"),
        keySpaceColor = Color.parseColor("#3B0764"),
        textColorPrimary = Color.parseColor("#F3E8FF"),
        textColorSecondary = Color.parseColor("#C084FC"),
        actionTextColor = Color.parseColor("#FFFFFF"),
        suggestionBgColor = Color.parseColor("#2E1065"),
        suggestionTextColor = Color.parseColor("#F3E8FF"),
        popupBgColor = Color.parseColor("#3B0764"),
        popupTextColor = Color.parseColor("#F3E8FF"),
        rippleColor = Color.parseColor("#6B21A8"),
        isDark = true
    ),
    PASTEL_LAVENDER(
        id = "pastel_lavender",
        displayName = "Pastel Lavender",
        backgroundColor = Color.parseColor("#F5F3FF"),
        keyNormalColor = Color.parseColor("#FFFFFF"),
        keySpecialColor = Color.parseColor("#EDE9FE"),
        keyActionColor = Color.parseColor("#8B5CF6"),
        keySpaceColor = Color.parseColor("#FFFFFF"),
        textColorPrimary = Color.parseColor("#4C1D95"),
        textColorSecondary = Color.parseColor("#8B5CF6"),
        actionTextColor = Color.parseColor("#FFFFFF"),
        suggestionBgColor = Color.parseColor("#F5F3FF"),
        suggestionTextColor = Color.parseColor("#4C1D95"),
        popupBgColor = Color.parseColor("#FFFFFF"),
        popupTextColor = Color.parseColor("#4C1D95"),
        rippleColor = Color.parseColor("#DDD6FE"),
        isDark = false
    ),
    SUNSET_GLOW(
        id = "sunset_glow",
        displayName = "Sunset Orange",
        backgroundColor = Color.parseColor("#1F1928"),
        keyNormalColor = Color.parseColor("#2D2238"),
        keySpecialColor = Color.parseColor("#3D2B4D"),
        keyActionColor = Color.parseColor("#F97316"),
        keySpaceColor = Color.parseColor("#2D2238"),
        textColorPrimary = Color.parseColor("#FFEDD5"),
        textColorSecondary = Color.parseColor("#FB923C"),
        actionTextColor = Color.parseColor("#FFFFFF"),
        suggestionBgColor = Color.parseColor("#1F1928"),
        suggestionTextColor = Color.parseColor("#FFEDD5"),
        popupBgColor = Color.parseColor("#2D2238"),
        popupTextColor = Color.parseColor("#FFEDD5"),
        rippleColor = Color.parseColor("#EA580C"),
        isDark = true
    ),
    ROYAL_GOLD(
        id = "royal_gold",
        displayName = "Luxury Gold & Black",
        backgroundColor = Color.parseColor("#121212"),
        keyNormalColor = Color.parseColor("#1E1E1E"),
        keySpecialColor = Color.parseColor("#2A2A2A"),
        keyActionColor = Color.parseColor("#EAB308"),
        keySpaceColor = Color.parseColor("#1E1E1E"),
        textColorPrimary = Color.parseColor("#FEF08A"),
        textColorSecondary = Color.parseColor("#CA8A04"),
        actionTextColor = Color.parseColor("#121212"),
        suggestionBgColor = Color.parseColor("#121212"),
        suggestionTextColor = Color.parseColor("#FEF08A"),
        popupBgColor = Color.parseColor("#1E1E1E"),
        popupTextColor = Color.parseColor("#FEF08A"),
        rippleColor = Color.parseColor("#A16207"),
        isDark = true
    ),
    SNOW_LIGHT(
        id = "snow_light",
        displayName = "Clean Snow White",
        backgroundColor = Color.parseColor("#F8FAFC"),
        keyNormalColor = Color.parseColor("#FFFFFF"),
        keySpecialColor = Color.parseColor("#E2E8F0"),
        keyActionColor = Color.parseColor("#2563EB"),
        keySpaceColor = Color.parseColor("#FFFFFF"),
        textColorPrimary = Color.parseColor("#0F172A"),
        textColorSecondary = Color.parseColor("#64748B"),
        actionTextColor = Color.parseColor("#FFFFFF"),
        suggestionBgColor = Color.parseColor("#F8FAFC"),
        suggestionTextColor = Color.parseColor("#0F172A"),
        popupBgColor = Color.parseColor("#FFFFFF"),
        popupTextColor = Color.parseColor("#0F172A"),
        rippleColor = Color.parseColor("#CBD5E1"),
        isDark = false
    );

    companion object {
        fun fromId(id: String?): KeyboardTheme {
            return values().firstOrNull { it.id == id } ?: AMOLED_MIDNIGHT
        }
    }
}
